export const jobs = [
    {id: 1, title:"Customer Support Executive", company_name:"Teleperformance (TP)", location:"Remote", 
        description:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non nisl lectus. Sed neque metus, tempus sit amet vulputate et, ultrices a leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus odio nisi, interdum sed elit et, pulvinar placerat nulla. Praesent nec consequat metus, lacinia commodo justo. Morbi gravida dui ante, ac ultrices erat suscipit a. Pellentesque pulvinar ligula ac semper consectetur.

Nulla dui velit, malesuada quis consequat nec, varius ut mauris. Curabitur blandit feugiat magna. Pellentesque mollis massa vitae libero malesuada dictum. Quisque maximus, augue a viverra pharetra, libero est congue velit, sed tempus nulla tortor quis enim. Maecenas vitae arcu elementum, pulvinar ipsum eget, vulputate est. Mauris diam diam, bibendum a tristique quis, molestie nec sem. Sed semper, erat eu semper varius, erat nibh luctus sapien, id rutrum felis felis a turpis.

Vestibulum congue nisi sapien. Praesent non consequat orci. Phasellus lacinia tellus est, vel tristique libero dictum ut. Integer volutpat sagittis arcu, eu aliquet sem fermentum eget. In ultrices tellus nec ligula tincidunt, sit amet dictum lectus mattis. Proin risus nulla, faucibus id dictum ut, luctus in risus. Aenean rutrum purus nec ullamcorper porttitor. In aliquet et felis sed tempus. Vestibulum commodo, massa et scelerisque laoreet, purus massa rhoncus nisl, vel pulvinar tortor risus vitae justo. Mauris accumsan convallis feugiat. Ut erat tellus, ultricies id euismod sed, cursus quis odio. Etiam semper augue pretium, rutrum diam at, aliquam sapien. Aliquam semper tortor nec sem auctor, nec volutpat tortor tincidunt.

`
    },
    {id: 2, title:"Title 2", company_name:"Company Name 2", location:"Job Location 2", 
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rutrum augue vitae efficitur maximus. Aenean a enim quis nisi finibus vestibulum at at risus. Suspendisse ullamcorper, lacus vitae fringilla ultrices, sapien elit malesuada urna, id elementum nisl nulla at lectus. Integer tincidunt libero purus, sed placerat justo mollis eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc pellentesque, turpis nec consectetur eleifend, mi nisl tempor quam, sit amet luctus tellus diam sit amet tellus. Mauris at rutrum purus, fringilla tempus nisl. Vivamus quis lacinia tortor. Suspendisse nec lectus venenatis libero viverra posuere. Sed sit amet leo molestie metus lobortis eleifend. Nullam efficitur tristique eros. Sed efficitur eros eu finibus sollicitudin. Donec dictum at elit vel laoreet. Nulla facilisis eros ut varius scelerisque. Integer tincidunt iaculis maximus. Etiam blandit non enim porta eleifend."
    },
    {id: 3, title:"Title 3", company_name:"Company Name 3", location:"Job Location 3", 
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rutrum augue vitae efficitur maximus. Aenean a enim quis nisi finibus vestibulum at at risus. Suspendisse ullamcorper, lacus vitae fringilla ultrices, sapien elit malesuada urna, id elementum nisl nulla at lectus. Integer tincidunt libero purus, sed placerat justo mollis eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc pellentesque, turpis nec consectetur eleifend, mi nisl tempor quam, sit amet luctus tellus diam sit amet tellus. Mauris at rutrum purus, fringilla tempus nisl. Vivamus quis lacinia tortor. Suspendisse nec lectus venenatis libero viverra posuere. Sed sit amet leo molestie metus lobortis eleifend. Nullam efficitur tristique eros. Sed efficitur eros eu finibus sollicitudin. Donec dictum at elit vel laoreet. Nulla facilisis eros ut varius scelerisque. Integer tincidunt iaculis maximus. Etiam blandit non enim porta eleifend."
    },
    {id: 4, title:"Title 4", company_name:"Company Name 4", location:"Job Location 4", 
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rutrum augue vitae efficitur maximus. Aenean a enim quis nisi finibus vestibulum at at risus. Suspendisse ullamcorper, lacus vitae fringilla ultrices, sapien elit malesuada urna, id elementum nisl nulla at lectus. Integer tincidunt libero purus, sed placerat justo mollis eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc pellentesque, turpis nec consectetur eleifend, mi nisl tempor quam, sit amet luctus tellus diam sit amet tellus. Mauris at rutrum purus, fringilla tempus nisl. Vivamus quis lacinia tortor. Suspendisse nec lectus venenatis libero viverra posuere. Sed sit amet leo molestie metus lobortis eleifend. Nullam efficitur tristique eros. Sed efficitur eros eu finibus sollicitudin. Donec dictum at elit vel laoreet. Nulla facilisis eros ut varius scelerisque. Integer tincidunt iaculis maximus. Etiam blandit non enim porta eleifend."
    },
    {id: 5, title:"Title 5", company_name:"Company Name 5", location:"Job Location 5", 
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rutrum augue vitae efficitur maximus. Aenean a enim quis nisi finibus vestibulum at at risus. Suspendisse ullamcorper, lacus vitae fringilla ultrices, sapien elit malesuada urna, id elementum nisl nulla at lectus. Integer tincidunt libero purus, sed placerat justo mollis eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc pellentesque, turpis nec consectetur eleifend, mi nisl tempor quam, sit amet luctus tellus diam sit amet tellus. Mauris at rutrum purus, fringilla tempus nisl. Vivamus quis lacinia tortor. Suspendisse nec lectus venenatis libero viverra posuere. Sed sit amet leo molestie metus lobortis eleifend. Nullam efficitur tristique eros. Sed efficitur eros eu finibus sollicitudin. Donec dictum at elit vel laoreet. Nulla facilisis eros ut varius scelerisque. Integer tincidunt iaculis maximus. Etiam blandit non enim porta eleifend."
    }
]